module.exports = [
  ['re', 'internal/re', 're'],
  ['src', 'internal/re', 'src'],
  ['tokens', 'internal/re', 't'],
  ['SEMVER_SPEC_VERSION', 'internal/constants', 'SEMVER_SPEC_VERSION'],
  ['SemVer', 'classes/semver'],
  ['compareIdentifiers', 'internal/identifiers', 'compareIdentifiers'],
  ['rcompareIdentifiers', 'internal/identifiers', 'rcompareIdentifiers'],
  ['parse', 'functions/parse'],
  ['valid', 'functions/valid'],
  ['clean', 'functions/clean'],
  ['inc', 'functions/inc'],
  ['diff', 'functions/diff'],
  ['major', 'functions/major'],
  ['minor', 'functions/minor'],
  ['patch', 'functions/patch'],
  ['prerelease', 'functions/prerelease'],
  ['compare', 'functions/compare'],
  ['rcompare', 'functions/rcompare'],
  ['compareLoose', 'functions/compare-loose'],
  ['compareBuild', 'functions/compare-build'],
  ['sort', 'functions/sort'],
  ['rsort', 'functions/rsort'],
  ['gt', 'functions/gt'],
  ['lt', 'functions/lt'],
  ['eq', 'functions/eq'],
  ['neq', 'functions/neq'],
  ['gte', 'functions/gte'],
  ['lte', 'functions/lte'],
  ['cmp', 'functions/cmp'],
  ['coerce', 'functions/coerce'],
  ['Comparator', 'classes/comparator'],
  ['Range', 'classes/range'],
  ['satisfies', 'functions/satisfies'],
  ['toComparators', 'ranges/to-comparators'],
  ['maxSatisfying', 'ranges/max-satisfying'],
  ['minSatisfying', 'ranges/min-satisfying'],
  ['minVersion', 'ranges/min-version'],
  ['validRange', 'ranges/valid'],
  ['outside', 'ranges/outside'],
  ['gtr', 'ranges/gtr'],
  ['ltr', 'ranges/ltr'],
  ['intersects', 'ranges/intersects'],
]
