// just pre-load all the stuff that index.js lazily exports
export { default as SemVer } from './classes/semver.js'
export { default as parse } from './functions/parse.js'
export { default as valid } from './functions/valid.js'
export { default as clean } from './functions/clean.js'
export { default as inc } from './functions/inc.js'
export { default as diff } from './functions/diff.js'
export { default as major } from './functions/major.js'
export { default as minor } from './functions/minor.js'
export { default as patch } from './functions/patch.js'
export { default as prerelease } from './functions/prerelease.js'
export { default as compare } from './functions/compare.js'
export { default as rcompare } from './functions/rcompare.js'
export { default as compareLoose } from './functions/compare-loose.js'
export { default as compareBuild } from './functions/compare-build.js'
export { default as sort } from './functions/sort.js'
export { default as rsort } from './functions/rsort.js'
export { default as gt } from './functions/gt.js'
export { default as lt } from './functions/lt.js'
export { default as eq } from './functions/eq.js'
export { default as neq } from './functions/neq.js'
export { default as gte } from './functions/gte.js'
export { default as lte } from './functions/lte.js'
export { default as cmp } from './functions/cmp.js'
export { default as coerce } from './functions/coerce.js'
export { default as Comparator } from './classes/comparator.js'
export { default as Range } from './classes/range.js'
export { default as satisfies } from './functions/satisfies.js'
export { default as toComparators } from './ranges/to-comparators.js'
export { default as maxSatisfying } from './ranges/max-satisfying.js'
export { default as minSatisfying } from './ranges/min-satisfying.js'
export { default as minVersion } from './ranges/min-version.js'
export { default as validRange } from './ranges/valid.js'
export { default as outside } from './ranges/outside.js'
export { default as gtr } from './ranges/gtr.js'
export { default as ltr } from './ranges/ltr.js'
export { default as intersects } from './ranges/intersects.js'
export { default as simplifyRange } from './ranges/simplify.js'
export { default as subset } from './ranges/subset.js'
export { re, src, t as tokens } from './internal/re.js'
export { SEMVER_SPEC_VERSION, RELEASE_TYPES } from './internal/constants.js'
export { compareIdentifiers, rcompareIdentifiers } from './internal/identifiers.js'
